import type { MetadataRoute } from "next";
import { MANIFEST_BACKGROUND_COLOR, MANIFEST_THEME_COLOR } from "@/lib/theme-tokens";

/**
 * Next 15 metadata route — served at /manifest.webmanifest.
 *
 * Icons are placeholder glyph tiles (public/icons/, generated by a boring
 * "K" tile, not hand-designed) so this ships before a custom visual design
 * lands. Swap the PNGs in public/icons/ and the colors in
 * lib/theme-tokens.ts when the design arrives — nothing else needs to change.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Karakos",
    short_name: "Karakos",
    description: "Karakos dashboard",
    start_url: "/",
    scope: "/",
    id: "/",
    display: "standalone",
    background_color: MANIFEST_BACKGROUND_COLOR,
    theme_color: MANIFEST_THEME_COLOR,
    icons: [
      {
        src: "/icons/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
