#!/usr/bin/env bash
# Regenerate docs/migration-inventory.md from the release tags (no hand typing).
set -euo pipefail
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TAGS=(v1.0.0 v1.1 v1.1.0 v1.1.1 v1.2 v1.3 v1.4.0 v1.4.1 v1.5.0)
J="$(mktemp -d)"; trap 'rm -rf "$J"' EXIT
for t in "${TAGS[@]}"; do "$REPO/tools/inventory-tag.sh" "$t" --json > "$J/$t.json"; done
{
cat <<'HDR'
# Migration inventory (generated)

Generated by `tools/inventory-all.sh` (per tag: `tools/inventory-tag.sh <tag>`).
Do not edit by hand. Tables and columns are produced by executing each tag's own
`CREATE TABLE` statements and `ensure_column()` calls in a throwaway sqlite.

## Layout buckets

Tags are grouped on the **migration-relevant** facts: compose mounts, named volumes
and the table/column set. Hooks, entrypoint and `.env` drift between tags (listed
per tag below) but change nothing the migrator moves, so they do not split a bucket.
Strict row identity would give more buckets; this is a deliberate choice.

HDR
python3 - "$J" "${TAGS[@]}" <<'PY'
import hashlib, json, sys
j, tags = sys.argv[1], sys.argv[2:]
F = {t: json.load(open(f"{j}/{t}.json")) for t in tags}
def key(f):
    tabs = {k.split(":", 1)[1]: v for k, v in f["tables"].items() if "sqlite_" not in k}
    # tables per source file => per database; mcp/tools-server tables are not 1.x user data
    tabs = {k: v for k, v in f["tables"].items() if "sqlite_" not in k and not k.startswith("mcp/")}
    return hashlib.md5(json.dumps([f["mounts"], f["named_volumes"], tabs], sort_keys=True).encode()).hexdigest()
order, groups = [], {}
for t in tags:
    k = key(F[t])
    if k not in groups: order.append(k)
    groups.setdefault(k, []).append(t)
names = {0: "1.0", 1: "1.3", 2: "1.5"}
print("| bucket | tags | detect fingerprint (`lib/migrate/detect.py`) |\n|---|---|---|")
fp = {"1.0": "compose mounts `..:/workspace` (whole checkout); no rate_limit_state/turn_events",
      "1.3": "compose mounts `../config` + `../agents`, volumes data/logs/inbox; no rate_limit_state/turn_events",
      "1.5": "`rate_limit_state` or `turn_events` table in the agent db"}
for i, k in enumerate(order):
    n = names.get(i, f"b{i}")
    print(f"| {n} | {', '.join(groups[k])} | {fp.get(n, '')} |")
print("\nColumns that differ between adjacent tags:\n")
for a, b in zip(tags, tags[1:]):
    d = [x for x in F[a] if x != "tag" and F[a][x] != F[b][x]]
    print(f"- `{a}` -> `{b}`: {', '.join(d) or 'identical'}")
print()
PY
cat <<'NOTE'
Findings that shape `05_layout`:

- In the 1.0 bucket `data/` is already the `karakos-data` named volume (the second
  mount layers over the `..:/workspace` bind). What lives in the user's checkout is
  `config/`, `agents/`, `.karakos/`, `logs/` and `inbox/`; those are what 2.0 either
  moves into the `karakos-logs`/`karakos-inbox` volumes or, with `--keep-bind`,
  keeps mounted from the host path.
- `.karakos/config.json` is tracked in every tag, so `.karakos/` does not fingerprint a version.
- The `.env` names are identical from v1.3 on; no variable is renamed across the
  nine tags (v1.2 drops `ANTHROPIC_API_KEY`, v1.3 adds `SESSION_SECRET` and `GMAIL_WEBHOOK_SECRET`).

NOTE
echo "## Per-tag tables"; echo
for t in "${TAGS[@]}"; do "$REPO/tools/inventory-tag.sh" "$t"; echo; done
} > "$REPO/docs/migration-inventory.md"
